In [64]:
import torch
import numpy as np

In [4]:
x = torch.rand(5,3)

In [5]:
x

tensor([[0.1548, 0.7831, 0.4702],
        [0.4144, 0.5198, 0.5823],
        [0.8071, 0.8574, 0.2671],
        [0.1107, 0.8574, 0.7235],
        [0.0949, 0.5352, 0.0087]])

tensor([[0.1548, 0.7831, 0.4702],
        [0.4144, 0.5198, 0.5823],
        [0.8071, 0.8574, 0.2671],
        [0.1107, 0.8574, 0.7235],
        [0.0949, 0.5352, 0.0087]])

In [8]:
torch.cuda.is_available()

False

In [18]:
x= torch.empty(10)


In [20]:
x

tensor([-1.0419e+28,  4.5853e-41, -1.0420e+28,  4.5853e-41, -1.0419e+28,
         4.5853e-41, -1.0411e+28,  4.5853e-41, -1.0422e+28,  4.5853e-41])

In [25]:
x = torch.rand(2,2)
x

tensor([[0.7038, 0.5945],
        [0.7644, 0.5447]])

In [26]:
x = torch.zeros(2,2)

In [27]:
x

tensor([[0., 0.],
        [0., 0.]])

In [29]:
x.size()

torch.Size([2, 2])

In [30]:
x = torch.tensor([1,2,3,4,5])

In [31]:
x

tensor([1, 2, 3, 4, 5])

In [33]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x+y

tensor([[1.4396, 1.0148],
        [1.2372, 0.2954]])

In [34]:
x

tensor([[0.4418, 0.2129],
        [0.8392, 0.2212]])

In [35]:
y

tensor([[0.9979, 0.8019],
        [0.3980, 0.0743]])

In [36]:
k = torch.add(x,y)

In [37]:
k

tensor([[1.4396, 1.0148],
        [1.2372, 0.2954]])

In [39]:
y.add_(x) # inplace addition 

tensor([[1.4396, 1.0148],
        [1.2372, 0.2954]])

In [40]:
y.mul_(x)

tensor([[0.6360, 0.2160],
        [1.0383, 0.0653]])

In [41]:
y

tensor([[0.6360, 0.2160],
        [1.0383, 0.0653]])

In [42]:
y.div_(x)

tensor([[1.4396, 1.0148],
        [1.2372, 0.2954]])

In [45]:
x[:,0]

tensor([0.4418, 0.8392])

In [46]:
x

tensor([[0.4418, 0.2129],
        [0.8392, 0.2212]])

In [51]:
x = torch.rand(5,5)

In [52]:
x

tensor([[0.7862, 0.3414, 0.9490, 0.2727, 0.4378],
        [0.4011, 0.3286, 0.6405, 0.1518, 0.7475],
        [0.0968, 0.3792, 0.2088, 0.8460, 0.6801],
        [0.5139, 0.8783, 0.6955, 0.4491, 0.3945],
        [0.3098, 0.1996, 0.9347, 0.9462, 0.5152]])

In [55]:
x1 = x.view(25)# reshaping a tensor

In [56]:
x1

tensor([0.7862, 0.3414, 0.9490, 0.2727, 0.4378, 0.4011, 0.3286, 0.6405, 0.1518,
        0.7475, 0.0968, 0.3792, 0.2088, 0.8460, 0.6801, 0.5139, 0.8783, 0.6955,
        0.4491, 0.3945, 0.3098, 0.1996, 0.9347, 0.9462, 0.5152])

In [62]:
x = x.view(25)

In [63]:
x

tensor([0.7862, 0.3414, 0.9490, 0.2727, 0.4378, 0.4011, 0.3286, 0.6405, 0.1518,
        0.7475, 0.0968, 0.3792, 0.2088, 0.8460, 0.6801, 0.5139, 0.8783, 0.6955,
        0.4491, 0.3945, 0.3098, 0.1996, 0.9347, 0.9462, 0.5152])

In [65]:
a = torch.ones(5)

In [66]:
a

tensor([1., 1., 1., 1., 1.])

In [67]:
b = a.numpy()

In [68]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [69]:
# if the tensor is on cpu not gpu, both objects have same memory location 

In [70]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [71]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [72]:
# change in a -> change in b 


In [73]:
# if you want to optimize sny tensor we have to set require_grad to true

In [75]:
x = torch.ones(5,requires_grad = True)

In [77]:
x = torch.rand(4,3, requires_grad=True)

In [78]:
x

tensor([[0.3910, 0.3687, 0.2287],
        [0.5890, 0.5110, 0.4971],
        [0.7672, 0.5090, 0.9396],
        [0.2801, 0.9281, 0.4716]], requires_grad=True)

## autograd package

In [84]:
x = torch.rand(5,5, requires_grad=True)

In [85]:
x

tensor([[0.5635, 0.9481, 0.5907, 0.0808, 0.7994],
        [0.0551, 0.9632, 0.7353, 0.2971, 0.2257],
        [0.8988, 0.2630, 0.4730, 0.9986, 0.6421],
        [0.5011, 0.9367, 0.7896, 0.3333, 0.9210],
        [0.8219, 0.2627, 0.8552, 0.8712, 0.9136]], requires_grad=True)

In [86]:
z = x+3

In [87]:
z

tensor([[3.5635, 3.9481, 3.5907, 3.0808, 3.7994],
        [3.0551, 3.9632, 3.7353, 3.2971, 3.2257],
        [3.8988, 3.2630, 3.4730, 3.9986, 3.6421],
        [3.5011, 3.9367, 3.7896, 3.3333, 3.9210],
        [3.8219, 3.2627, 3.8552, 3.8712, 3.9136]], grad_fn=<AddBackward0>)

In [88]:
z1 = x*x*x*3

In [91]:
z1

tensor([[5.3669e-01, 2.5566e+00, 6.1835e-01, 1.5802e-03, 1.5326e+00],
        [5.0113e-04, 2.6812e+00, 1.1925e+00, 7.8696e-02, 3.4513e-02],
        [2.1783e+00, 5.4580e-02, 3.1752e-01, 2.9875e+00, 7.9412e-01],
        [3.7743e-01, 2.4656e+00, 1.4768e+00, 1.1105e-01, 2.3434e+00],
        [1.6657e+00, 5.4404e-02, 1.8762e+00, 1.9836e+00, 2.2874e+00]],
       grad_fn=<MulBackward0>)

In [95]:
z1 = z1.mean()

In [96]:
z1

tensor(1.2083, grad_fn=<MeanBackward0>)

In [97]:
z1.backward()

In [102]:
grad = x.grad

In [101]:
x

tensor([[0.5635, 0.9481, 0.5907, 0.0808, 0.7994],
        [0.0551, 0.9632, 0.7353, 0.2971, 0.2257],
        [0.8988, 0.2630, 0.4730, 0.9986, 0.6421],
        [0.5011, 0.9367, 0.7896, 0.3333, 0.9210],
        [0.8219, 0.2627, 0.8552, 0.8712, 0.9136]], requires_grad=True)

## backprop

In [105]:
x = torch.tensor(1.0)
y= torch.tensor(2.0)


w = torch.tensor(1.0 , requires_grad = True)

In [112]:
y_ht = w*x
loss= (y-y_ht)**2

In [113]:
y_ht, loss

(tensor(1., grad_fn=<MulBackward0>), tensor(1., grad_fn=<PowBackward0>))

In [114]:
loss.backward()

In [124]:
grad_w = w.grad

In [125]:
grad_w

tensor(-2.)

In [126]:
np.ones(5)

array([1., 1., 1., 1., 1.])